/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;
import aplikasigudang.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        
        if(ConfigDB.isLoggedIn==false){
            mnLogout.setVisible(false);
            usernameDisplay.setText("Anda belum login");
        } else {
            mnLogin.setVisible(false);
            usernameDisplay.setText("Login sebagai: " + ConfigDB.loginUsername);
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        usernameDisplay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnBarang = new javax.swing.JMenuItem();
        mnSupplier = new javax.swing.JMenuItem();
        mnGudang = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnBarangMasuk = new javax.swing.JMenuItem();
        mnBarangKeluar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnLaporanBarang = new javax.swing.JMenuItem();
        mnLaporanSupplier = new javax.swing.JMenuItem();
        mnLaporanGudang = new javax.swing.JMenuItem();
        mnLaporanBarangMasuk = new javax.swing.JMenuItem();
        mnLaporanBarangKeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnLogin = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        setBackground(new java.awt.Color(143, 197, 251));

        jPanel1.setBackground(new java.awt.Color(56, 168, 206));

        jPanel2.setBackground(new java.awt.Color(199, 217, 218));

        usernameDisplay.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        usernameDisplay.setForeground(new java.awt.Color(5, 101, 134));
        usernameDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameDisplay.setText("Login status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addComponent(usernameDisplay)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameDisplay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 52)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aplikasi Gudang (Inventory)");

        jLabel1.setText("M. Ihsan Ramadhan (19630168)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Master Data");

        mnBarang.setText("Data Barang");
        mnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangActionPerformed(evt);
            }
        });
        jMenu1.add(mnBarang);

        mnSupplier.setText("Data Supplier");
        mnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSupplierActionPerformed(evt);
            }
        });
        jMenu1.add(mnSupplier);

        mnGudang.setText("Data Gudang");
        mnGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGudangActionPerformed(evt);
            }
        });
        jMenu1.add(mnGudang);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Transaksi");

        mnBarangMasuk.setText("Transaksi Barang Masuk");
        mnBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangMasukActionPerformed(evt);
            }
        });
        jMenu4.add(mnBarangMasuk);

        mnBarangKeluar.setText("Transaksi Barang Keluar");
        mnBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangKeluarActionPerformed(evt);
            }
        });
        jMenu4.add(mnBarangKeluar);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Laporan");

        mnLaporanBarang.setText("Laporan Data Barang");
        mnLaporanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanBarangActionPerformed(evt);
            }
        });
        jMenu3.add(mnLaporanBarang);

        mnLaporanSupplier.setText("Laporan Data Supplier");
        mnLaporanSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanSupplierActionPerformed(evt);
            }
        });
        jMenu3.add(mnLaporanSupplier);

        mnLaporanGudang.setText("Laporan Data Gudang");
        mnLaporanGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanGudangActionPerformed(evt);
            }
        });
        jMenu3.add(mnLaporanGudang);

        mnLaporanBarangMasuk.setText("Laporan Transaksi Barang Masuk");
        mnLaporanBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanBarangMasukActionPerformed(evt);
            }
        });
        jMenu3.add(mnLaporanBarangMasuk);

        mnLaporanBarangKeluar.setText("Laporan Transaksi Barang Keluar");
        mnLaporanBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanBarangKeluarActionPerformed(evt);
            }
        });
        jMenu3.add(mnLaporanBarangKeluar);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Akun");

        mnLogin.setText("Login");
        mnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLoginActionPerformed(evt);
            }
        });
        jMenu2.add(mnLogin);

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenu2.add(mnLogout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void mnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangActionPerformed
        // TODO add your handling code here:
        new Barang().setVisible(true);
    }//GEN-LAST:event_mnBarangActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        // TODO add your handling code here:
        ConfigDB.logout(this);
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSupplierActionPerformed
        // TODO add your handling code here:
        new Supplier().setVisible(true);
    }//GEN-LAST:event_mnSupplierActionPerformed

    private void mnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLoginActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnLoginActionPerformed

    private void mnGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGudangActionPerformed
        // TODO add your handling code here:
        new Gudang().setVisible(true);
    }//GEN-LAST:event_mnGudangActionPerformed

    private void mnBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangMasukActionPerformed
        try {
            // TODO add your handling code here:
            new BarangMasuk().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnBarangMasukActionPerformed

    private void mnBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangKeluarActionPerformed
        try {
            // TODO add your handling code here:
            new BarangKeluar().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnBarangKeluarActionPerformed

    private void mnLaporanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanBarangActionPerformed
        // TODO add your handling code here:
         ConfigDB.tampilLaporan("src/laporan/laporanBarang.jrxml","SELECT*FROM barang");
    }//GEN-LAST:event_mnLaporanBarangActionPerformed

    private void mnLaporanSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanSupplierActionPerformed
        // TODO add your handling code here:
        ConfigDB.tampilLaporan("src/laporan/laporanSupplier.jrxml","SELECT*FROM supplier");
    }//GEN-LAST:event_mnLaporanSupplierActionPerformed

    private void mnLaporanGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanGudangActionPerformed
        // TODO add your handling code here:
        ConfigDB.tampilLaporan("src/laporan/laporanGudang.jrxml","SELECT*FROM gudang");
    }//GEN-LAST:event_mnLaporanGudangActionPerformed

    private void mnLaporanBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanBarangMasukActionPerformed
        // TODO add your handling code here:
        new FilterTanggal("Laporan Barang Masuk").setVisible(true);
//        String sqlBarangMasuk = "SELECT barang_masuk.id_bm, barang_masuk.tanggal, barang.kode_barang, barang.nama_barang, supplier.kode_supplier, supplier.nama_supplier, barang_masuk.jumlah, barang_masuk.keterangan FROM barang_masuk INNER JOIN barang ON barang_masuk.kode_barang = barang.kode_barang INNER JOIN supplier ON barang_masuk.kode_supplier = supplier.kode_supplier";
//        ConfigDB.tampilLaporan("src/laporan/laporanBarangMasuk.jrxml", sqlBarangMasuk);

    }//GEN-LAST:event_mnLaporanBarangMasukActionPerformed

    private void mnLaporanBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanBarangKeluarActionPerformed
        // TODO add your handling code here:
        new FilterTanggal("Laporan Barang Keluar").setVisible(true);
//        String sqlBarangKeluar = "SELECT barang_keluar.id_bk, barang_keluar.tanggal, barang.kode_barang, barang.nama_barang, gudang.kode_gudang, gudang.nama_gudang, barang_keluar.jumlah, barang_keluar.keterangan FROM barang_keluar INNER JOIN barang ON barang_keluar.kode_barang = barang.kode_barang INNER JOIN gudang ON barang_keluar.kode_gudang = gudang.kode_gudang";
//        ConfigDB.tampilLaporan("src/laporan/laporanBarangKeluar.jrxml", sqlBarangKeluar);
    }//GEN-LAST:event_mnLaporanBarangKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem mnBarang;
    private javax.swing.JMenuItem mnBarangKeluar;
    private javax.swing.JMenuItem mnBarangMasuk;
    private javax.swing.JMenuItem mnGudang;
    private javax.swing.JMenuItem mnLaporanBarang;
    public static javax.swing.JMenuItem mnLaporanBarangKeluar;
    public static javax.swing.JMenuItem mnLaporanBarangMasuk;
    private javax.swing.JMenuItem mnLaporanGudang;
    private javax.swing.JMenuItem mnLaporanSupplier;
    private javax.swing.JMenuItem mnLogin;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnSupplier;
    private javax.swing.JLabel usernameDisplay;
    // End of variables declaration//GEN-END:variables
}
